### PR TITLE
Calculate new salary.

### PR DESCRIPTION
**Pull request by I-codebyte**

### CODE REVIEW

**Comment by I-codebyte** [comment]
this calculate salary increase

**Review by joshuaunity — CHANGES_REQUESTED** [review]
This suggestion to include a function for percentage-based salary increments is good. However, it's worth mentioning that the assignment requires a function that allows for the input of a completely new numerical value to directly update an employee's salary.

**Comment by I-codebyte** [comment]
comment modified

**Comment by joshuaunity** [comment]
Yes I know but that's not the requirement in this case, you are meant to create a function that accepts a number which will be used to update the employee main salary, that way if I want to change an employee salary from 5000 to 24000 I can use that function.

Do you understand the goal now?

**Comment by I-codebyte** [comment]
> Yes I know but that's not the requirement in this case, you are meant to create a function that accepts a number which will be used to update the employee main salary, that way if I want to change an employee salary from 5000 to 24000 I can use that function.
> 
> Do you understand the goal now?

Like, let's say I want to increase or decrease the salary.
I will just call the function thus:
updateSalary(1000) 
And it will decrease or increase the salary, right?

**Comment by joshuaunity** [comment]
Yes exactly, then the new salary will be 1000

**Comment by joshuaunity** [comment]
You sent doing any plus or minus it's a direct update, if I put 1600 then the employee salary Should be updated to 1600

**Comment by I-codebyte** [comment]
code updated

**Review by joshuaunity — APPROVED** [review]

**Comment by joshuaunity** [comment]
Well done, now go and create a new branch with your GitHub username as the name of the branch

**Pull request merged**
