### PR TITLE
added a file that updates employee salary

### PR DESCRIPTION
**Pull request by Sheysi**

### CODE REVIEW

**Review by joshuaunity — CHANGES_REQUESTED** [review]
Hi, if you notice this function only.promts out the new salary it doesn't update the employee salary to this new one. To understand what I am saying console.log the employee salary after you run that your function and you will that it did not change to the new value you parser

**Comment by joshuaunity** [comment]
Also i just invited you this repo as a collaborator go ahead and accept the invite. Secondly creat a new branch for yourself, that branch should be the name of your GitHub username

**Comment by Sheysi** [comment]
I've updated the code as you said. It prints out the new salary when i console.log the employee salary

**Comment by joshuaunity** [comment]
Great, now create your own separate branch

**Pull request merged**
